In [8]:
import numpy as np

# 1. Tạo mảng 2 chiều 3x3 với các giá trị True
arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# 2. Tạo mảng 2 chiều từ mảng 1 chiều và chuyển cột 1 sang cột 3 và ngược lại
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3, 3))
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print(arr_1D)

[2 1 0 5 4 3 8 7 6]


In [10]:
# 3. Chuyển dòng 1 sang dòng 2 và ngược lại
arr_2D = arr_2D.swapaxes(0, 1)
print(arr_2D)

[[2 5 8]
 [1 4 7]
 [0 3 6]]


In [11]:
# 4. Đảo ngược các dòng của mảng 2 chiều
arr_2D = np.flipud(arr_2D)
print(arr_2D)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [12]:
# 5. Đảo ngược các cột của mảng 2 chiều
arr_2D = np.fliplr(arr_2D)
print(arr_2D)

[[6 3 0]
 [7 4 1]
 [8 5 2]]


In [13]:
# 6. Kiểm tra giá trị rỗng trong mảng
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_null_values = np.isnan(arr_2D_null).any()
print(arr_2D_null)

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]


In [14]:
# 7. Thay thế giá trị rỗng bằng 0 trong mảng
arr_2D_null = np.nan_to_num(arr_2D_null)
print(arr_2D_null)

[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
